### ISSUE TITLE
Can’t add a team subscription to myTBA on site

### ISSUE THREAD

**Issue by dragonruler1000** [the-blue-alliance/the-blue-alliance#5113] opened 2023-03-17 15:23 UTC
## Expected Behavior

Page saying team added

## Current Behavior

It’s giving me an 405 error every time I try it

## Steps to Reproduce (for bugs)

1. Go to the blue alliance website
2. Log in using a google account
3. Hit myTBA 
4. Hit mange
5. Select team
6. Hit save

## Context

It makes it so I can’t get notifications about updates for my team. 

## Your Environment

* Version used: latest live version as of fri mar 17 2023
* Environment name and version (e.g. Chrome 39, node.js 5.4): chrome version 109.0.5414.83
* Operating System and version (desktop or mobile): iPad 7 on iPad os 16.3.1

**Comment by gregmarra** [comment] 2023-03-18 23:48
Closing as duplicate of https://github.com/the-blue-alliance/the-blue-alliance/issues/4811

**Closed by gregmarra** 2023-03-18 23:48 UTC
