### ISSUE TITLE
Playoff bracket advancement wrong at 2022orore

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#4313] opened 2022-03-14 00:09 UTC
## Expected Behavior
Alliance 3 advanced to finals, but Alliance 2 is shown as advancing. District point calculations are wrong.

## Current Behavior
Alliance 2 shown as advancing, probably because match result data suggest they won the Semis.

## Steps to Reproduce (for bugs)
<img width="614" alt="image" src="https://user-images.githubusercontent.com/57101/158085498-a04ea2d9-8b16-494e-b154-40bb5598aa2b.png">

**Comment by miklast** [comment] 2022-03-17 18:36
Data is now all correct on FIRST's end.
https://frc-events.firstinspires.org/2022/ORORE/playoffs

**Comment by gregmarra** [comment] 2022-03-18 23:57
The FIRST API returns (or at least, https://www.thebluealliance.com/tasks/get/fmsapi_matches/2022orore displays)
> Alliances: {"red": {"teams": ["frc1540", "frc955", "frc5970"], "surrogates": [], "dqs": [], "score": 53}, "blue": {"teams": ["frc3674", "frc3812", "frc5468"], "surrogates": [], "dqs": [], "score": 28}}

Which is apparently the incorrect results, because https://frc-events.firstinspires.org/2022/ORORE/playoffs shows different data for Quarterfinals 7 which we call qf3m3)

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/57101/159098059-bd087e5c-9a6a-4fc6-9cff-f270329ae127.png">

**Comment by ZachOrr** [comment] 2022-03-31 14:38
Related to the root cause of https://github.com/the-blue-alliance/the-blue-alliance/issues/4313

**Comment by ZachOrr** [comment] 2022-05-17 05:10
This has been fixed with rescraping matches

**Closed by ZachOrr** 2022-05-17 05:10 UTC
