### ISSUE TITLE
Gameday URL Event Aliases broken on Safari

### ISSUE THREAD

**Issue by AustinShalit** [the-blue-alliance/the-blue-alliance#2419] opened 2019-03-01 22:16 UTC
When providing an alias link to gameday (`https://www.thebluealliance.com/gameday/2019caoc`), the `GamedayRedirectHandler` does not expand the URL into what it should be.

## Expected Behavior

Navigating to `/gameday/<alias>` will open the provided event in gameday.

## Current Behavior

The user is redirected to the default gameday page.

## Possible Solution

The issue should be here but I am abroad and cannot investigate more than browsing GitHub on my phone:

https://github.com/the-blue-alliance/the-blue-alliance/blob/1324e9e5b7c4ab21315bd00a768112991bada108/controllers/gameday_controller.py#L124-L129

**Comment by fangeugene** [comment] 2019-03-01 22:18
It works for me?

**Comment by AustinShalit** [comment] 2019-03-01 22:20
😕.  I just tried with Chrome and it worked. I guess this is a browser issue.  I am seeing this behavior when using Safari Version 12.0.3 (14606.4.5)

**Comment by ZachOrr** [comment] 2019-03-11 00:18
Unassigned myself - this seems like a thing on the domain level (Cloudflare related?). I can test a fix - but I can't reproduce in dev or on a staging instance.

**Comment by fangeugene** [comment] 2019-03-12 01:04
Fixed in https://github.com/the-blue-alliance/the-blue-alliance/commit/2c00bfdc6fbb7bdc2306f0e9e0b9840ca92c0c5e

**Closed by fangeugene** 2019-03-12 01:04 UTC

**Comment by AustinShalit** [comment] 2019-03-12 01:24
Also working for me 😄

**Comment by fangeugene** [comment] 2019-03-12 01:25
@AustinShalit did this just break, or has this been a problem for the last 2 years?

**Comment by AustinShalit** [comment] 2019-03-12 10:09
I think it has been a problem for a while but I rarely use the green redirect links so do not know for sure.
