### ISSUE TITLE
Match starting soon notifications sends dozens of times, sometimes not at all

### ISSUE THREAD

**Issue by team204frc** [the-blue-alliance/the-blue-alliance#5804] opened 2024-03-17 15:03 UTC
## Expected Behavior

The match starting soon (for example, "PAPHI Q35 Starting Soon") notification is sent once, a little before every match
## Current Behavior

The match starting soon notification is sent dozens of times before, during, and after the match, or is never sent at all

### Example Video

https://github.com/the-blue-alliance/the-blue-alliance/assets/122567894/1d1e210f-5b28-40a5-bea7-3ecf7e5baec9

## Possible Solution

No idea, am not familiar with TBA codebase or structure
## Steps to Reproduce (for bugs)

1. Subscribe to an event and a team (for me, PAPHI(fma chestnut hill) and 204)
2. ~Wait for a match~
3.
4.

## Context

I am either completely unaware about which match is upcoming or well too aware about a match that might not even be happening soon.
## Your Environment

* Version used: TBA for iOS v3.1.1 (99)
* Environment name and version (e.g. Chrome 39, node.js 5.4): n/a
* Operating System and version (desktop or mobile): iOS 17.3.1, iPhone 11 Pro
* Notification Test succeeded

**Comment by ZachOrr** [comment] 2024-03-17 17:36
Closing as a dupe of https://github.com/the-blue-alliance/the-blue-alliance/issues/5668 - please follow that issue for updates

**Closed by ZachOrr** 2024-03-17 17:36 UTC
