### ISSUE TITLE
2016 Einstein Typo

### ISSUE THREAD

**Issue by AndySheu** [the-blue-alliance/the-blue-alliance#1911] opened 2017-04-24 05:02 UTC
The 4th and 7th seeds are on the wrong side of the bracket. So the 4th seed turns into the 7th seed in the semifinals and vice versa.

<img width="524" alt="screen shot 2017-04-23 at 10 00 34 pm" src="https://cloud.githubusercontent.com/assets/9222176/25322938/60d17b62-2870-11e7-9d0b-db46087b7f47.png">

**Comment by fangeugene** [comment] 2017-04-24 05:12
Dupe of #1900

**Closed by fangeugene** 2017-04-24 05:12 UTC
