### ISSUE TITLE
Incorrect district rank

### ISSUE THREAD

**Issue by Moeez-Muhammad** [the-blue-alliance/the-blue-alliance#2479] opened 2019-03-23 23:42 UTC
District rank is displayed incorrectly on the team page and teams 3683 and 4476 are both shown as being first in the Ontario District.

## Expected Behavior

There shouldn't be two teams with the same rank.
## Current Behavior

Teams 3683 and 4476 are both displayed as being rank 1 in Ontario, even though 4476 is second. From that, every other team is moved up one rank, like 188 being displayed as rank 2, when it is in fact second.
![image](https://user-images.githubusercontent.com/26047425/54872944-b0eeee00-4da2-11e9-843c-c7a20f7beb6b.png)
![image](https://user-images.githubusercontent.com/26047425/54872948-bcdab000-4da2-11e9-8bd8-f8750747d8c4.png)
![image](https://user-images.githubusercontent.com/26047425/54872951-c2d09100-4da2-11e9-8b13-043558deb299.png)
![image](https://user-images.githubusercontent.com/26047425/54872953-c82ddb80-4da2-11e9-819b-8511ce48b0f5.png)

## Steps to Reproduce

1. Go to https://www.thebluealliance.com/team/3683/2019
2. Go to https://www.thebluealliance.com/team/4476/2019

## Context

I was viewing both team's pages and I was confused when both were displayed as rank 1. The actual ranking is only apparent by going to the district ranking or by comparing points.
## Your Environment

* Version used: This is on the website, so I'm assuming the master branch?
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 65.0.2 (64-bit)
* Operating System and version (desktop or mobile): Windows 8.1

**Comment by gregmarra** [comment] 2019-03-24 16:29
This issue was likely caused by caching. We probably cached an old version of one team's page, then ranks changed, and the cache hadn't cleared yet, so two teams were displayed as the first rank team. Cache generation times are displayed at the footer of pages.

Due to our caching behavior, this is a "won't fix". Future versions of the site are less likely to have this issue as we move towards a progressive web app.

**Closed by gregmarra** 2019-03-24 16:29 UTC
