### ISSUE TITLE
Cargo count is 0 while cargo points > 0

### ISSUE THREAD

**Issue by katzuv** [the-blue-alliance/the-blue-alliance#4291] opened 2022-03-05 08:07 UTC
Maybe I don't understand something, but at FIT District Waco 2022 match [Q31](https://www.thebluealliance.com/match/2022txwac_qm31), `Cargo Points > 0` but `Cargo Count = 0` for both alliances.

**Comment by josephtcoyle** [comment] 2022-03-06 14:30
Same issue occurs on Matches 17 and 42 of the Lake Superior Regional (2022mndu).
The Blue Alliance match page also shows the same problem - e.g. Auto Cargo Count = 0, Auto Cargo Points > 0
Additional detail from JSON snippet...
    "key": "2022mndu_qm42",
...
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCargoLowerBlue": 0,
        "autoCargoLowerFar": 0,
        "autoCargoLowerNear": 0,
        "autoCargoLowerRed": 0,
        "autoCargoPoints": 0,
        "autoCargoTotal": 0,
        "autoCargoUpperBlue": 0,
        "autoCargoUpperFar": 0,
        "autoCargoUpperNear": 0,
        "autoCargoUpperRed": 0,
        "autoPoints": 6,
        "autoTaxiPoints": 6,
        "cargoBonusRankingPoint": false,
        "endgamePoints": 6,
        "endgameRobot1": "None",
        "endgameRobot2": "None",
        "endgameRobot3": "Mid",
        "foulCount": 0,
        "foulPoints": 12,
        "hangarBonusRankingPoint": false,
        "matchCargoTotal": 0,
        "quintetAchieved": false,
        "rp": 0,
        "taxiRobot1": "Yes",
        "taxiRobot2": "Yes",
        "taxiRobot3": "Yes",
        "techFoulCount": 0,
        "teleopCargoLowerBlue": 0,
        "teleopCargoLowerFar": 0,
        "teleopCargoLowerNear": 0,
        "teleopCargoLowerRed": 0,
        "teleopCargoPoints": 15,
        "teleopCargoTotal": 0,
        "teleopCargoUpperBlue": 0,
        "teleopCargoUpperFar": 0,
        "teleopCargoUpperNear": 0,
        "teleopCargoUpperRed": 0,
        "teleopPoints": 21,
        "totalPoints": 39

**Comment by ZachOrr** [comment] 2022-03-07 00:44
> Maybe I don't understand something, but at FIT District Waco 2022 match [Q31](https://www.thebluealliance.com/match/2022txwac_qm31), `Cargo Points > 0` but `Cargo Count = 0` for both alliances.

This looks to match the data FIRST has at https://frc-events.firstinspires.org/2022/TXWAC/qualifications/31
<img width="834" alt="Screen Shot 2022-03-06 at 7 44 09 PM" src="https://user-images.githubusercontent.com/516458/156950039-0d57ca0e-90e0-48fa-9713-426e2a82bbba.png">

**Comment by ZachOrr** [comment] 2022-03-07 00:46
> Same issue occurs on Matches 17 and 42 of the Lake Superior Regional (2022mndu). The Blue Alliance match page also shows the same problem - e.g. Auto Cargo Count = 0, Auto Cargo Points > 0 

Same as the previous comment - it looks like this is the data FIRST has (doesn't have) for these two matches

<img width="839" alt="Screen Shot 2022-03-06 at 7 45 11 PM" src="https://user-images.githubusercontent.com/516458/156950117-080ee8f3-1247-44f3-bc4d-f25201982f37.png">

<img width="875" alt="Screen Shot 2022-03-06 at 7 45 23 PM" src="https://user-images.githubusercontent.com/516458/156950126-5a49bbf4-1fa4-4325-881e-17db896e207e.png">

**Comment by ZachOrr** [comment] 2022-03-07 00:47
Going to close this. I don't want to speculate on the cause of these - but if the data isn't upstream, we're not going to get it in the site.

If someone has this data and would like to submit it, we can try to get it on the site. We need to have some way to verify that it's accurate.

**Closed by ZachOrr** 2022-03-07 00:47 UTC
