### ISSUE TITLE
[WEB INTERFACE]: Error While Adding Team to MyTBA

### ISSUE THREAD

**Issue by foehammer127** [the-blue-alliance/the-blue-alliance#5090] opened 2023-03-12 03:00 UTC
# Description: 
I am unable to add a team to my My TBA profile using the web interface, as I am met with a HTTP 405 Error
on every attempt.

# Information:
Browser: Firefox 110.0.1 (64-bit)
Login Type: Google Oauth
OS: Linux x86_64

# Steps to Reproduce
1. Select Manage My TBA in the account settings on the web interface.
2. Select any Team Number in the teams tab. and add any event type. 
3. Select Save.
4. Be Met With The Following
![image](https://user-images.githubusercontent.com/44120040/224521714-ef76f0cd-6c76-4237-a136-74afabc0414f.png)

**Comment by qrAIhttps** [comment] 2023-03-13 17:57
I was able to reproduce the error with Google Chrome 110.0.5481.177 (Official Build) (arm64) on macOS ventura.

**Comment by foehammer127** [comment] 2023-03-14 23:41
What login type

**Comment by qrAIhttps** [comment] 2023-03-15 04:41
Google

**Comment by gregmarra** [comment] 2023-03-18 23:48
Closing as duplicate of https://github.com/the-blue-alliance/the-blue-alliance/issues/4811

**Closed by gregmarra** 2023-03-18 23:48 UTC
