### ISSUE TITLE
[Web Interface] Adding events to myTBA produces a 404 error

### ISSUE THREAD

**Issue by mrSiefen** [the-blue-alliance/the-blue-alliance#5092] opened 2023-03-12 03:58 UTC
Steps to reproduce:

1. Select myTBA from the nav bar
2. Select the manage myTBA button from the myTBA dashboard
3. Select that you want to add an event
4. Search for the event (I did Macomb and it found it)
5. Click on the search suggestion
6. 404 as shown below

**Comment by mrSiefen** [comment] 2023-03-12 04:01
![Screenshot_20230311_225100_Chrome](https://user-images.githubusercontent.com/115971660/224523558-833a755d-0395-424b-be16-f3aaeb9abd0f.jpg)

**Comment by mrSiefen** [comment] 2023-03-12 04:04
The endpoint link that causes the 404 is: https://www.thebluealliance.com/account/mytba/event/2023mimcc

**Comment by mrSiefen** [comment] 2023-03-12 04:08
I think what is happening is someone added hyperlinks in the event search drop-down for this and also possibly for adding teams as well (see #5090) both of these things try to add something to your myTBA via the web interface and both fail in different ways. In my case the event is not added to myTBA because of that hyperlink and it tries to go to the page that you would normally find it at after it was added properly. If I can screen record it tomorrow on my phone I will, but once you pick a search suggestion it jumps to that 404 page before you can hit save at the bottom of the myTBA event form. Users can't select a search choice and save it because of this so there is nothing to display and hence the 404.

**Comment by gregmarra** [comment] 2023-03-18 23:48
Closing as duplicate of https://github.com/the-blue-alliance/the-blue-alliance/issues/4811

**Comment by mrSiefen** [comment] 2023-03-18 23:57
This doesn't seem to be the same issue exactly. Are you really sure this is truly a duplicate? My issue seems solvable easily by not adding hyperlinks in the search results. The other issue you linked is over 2 years old and stuff unsolved which doesn't give me much hope.

**Comment by gregmarra** [comment] 2023-03-19 00:03
Hmm, I think things work in the app now, so I will switch what issue we track the py3 issues with to this one.

**Closed** 2024-01-01 21:09 UTC
