### ISSUE TITLE
Nearby seach finds too many teams

### ISSUE THREAD

**Issue by JackToaster** [the-blue-alliance/the-blue-alliance#2284] opened 2018-05-14 22:57 UTC
When a 'nearby team' search is executed with a 2500 mile radius, instead of finding a reasonable amount of teams, the search results show 16,780 teams (Far more than really exist), and many of the links do not work.
## Expected Behavior

The search should return the proper number of teams and working links for the pages of teams.

## Current Behavior

The search returns far too many teams (16780 teams from my location) and the links to pages after the teams that are really in the area are broken (Send the user to a 500 server error page).

## Possible Solution

I'm not sure how to solve it, but it seems that the search really works, but there is a bug counting/displaying the search results.

## Steps to Reproduce (for bugs)

1. Go to the 'Search Nearby' page: [https://www.thebluealliance.com/nearby?search_type=teams](https://www.thebluealliance.com/nearby?search_type=teams)
2. Enter a zip code/location (48178 caused the bug for me)
3. Set the distance to 2500mi
4. Press search

Example: [https://www.thebluealliance.com/nearby?year=2018&location=48178&range_limit=2500&search_type=teams](https://www.thebluealliance.com/nearby?year=2018&location=48178&range_limit=2500&search_type=teams)

## Context

This issue hasn't affected me greatly. I was trying to find the number of teams withing 2500 miles, but this bug prevents me from doing so.

## Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 57
* Operating System and version (desktop or mobile): Ubuntu 17.10 desktop

**Comment by ZachOrr** [comment] 2018-12-29 15:11
I can't reproduce this one - the provided link shows 531 teams. Feel free to comment if this is still a problem, but I'm going to close this out.

**Closed by ZachOrr** 2018-12-29 15:11 UTC

**Comment by ZachOrr** [comment] 2018-12-29 15:31
For tracking - I believe this was fixed with https://github.com/the-blue-alliance/the-blue-alliance/issues/2201
